### ISSUE TITLE
Cannot start server in dev mode

### ISSUE THREAD

**Issue by jgnoonan** [signalapp/ContactDiscoveryService-Icelake#5]
When I run the server in dev mode, it throws the following exception:

`2024-12-07 04:13:45,049 [scheduled-executor-thread-1] WARN  org.signal.cdsi.enclave.Enclave - Failed to renew attestation
java.util.concurrent.CompletionException: org.signal.libsignal.cds2.AttestationDataException: attestation data invalid: No evidence provided on handshake start
	at org.signal.cdsi.enclave.Enclave.lambda$renewAttestation$3(Enclave.java:194)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at org.signal.cdsi.enclave.Enclave.lambda$runAsync$18(Enclave.java:440)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.signal.libsignal.cds2.AttestationDataException: attestation data invalid: No evidence provided on handshake start
	at org.signal.libsignal.internal.Native.Cds2Metrics_extract(Native Method)
	at org.signal.libsignal.cds2.Cds2Metrics.extract(Cds2Metrics.java:31)
	at org.signal.cdsi.enclave.Enclave.publishAttestationMetrics(Enclave.java:216)
	at org.signal.cdsi.enclave.Enclave.lambda$renewAttestation$3(Enclave.java:192)
	... 8 common frames omitted`
	
	
My VM is an Azure Confidential Compute VM running Ubuntu 20.04.  I've installed the Intel SGX SDK, and the Intel AESM service is running.  Based on Microsoft Documentation, I installed the Azure DCAP client.  The sgx_default_qncl.conf looks as follows:

`{
  "pccs_url": "https://global.acccache.azure.net/sgx/certification/v4/",

  "use_secure_cert": true,

  "collateral_service": "https://global.acccache.azure.net/sgx/certification/v4/",

  "pccs_api_version": "3.1",

  "retry_times": 6,

  "retry_delay": 5,

  "local_pck_url": "http://169.254.169.254/metadata/THIM/sgx/certification/v4/",

  "pck_cache_expire_hours": 48,

  "custom_request_options" : {
       "get_cert" : {
          "headers": {
              "metadata": "true"
          },
          "params": {
             "api-version": "2021-07-22-preview"
         }
      }
   }
}`

How can I resolve this?

**Comment by jgnoonan** [comment]
I should note that the server does start, but then throws that exception.

**Comment by YXXS242417** [comment]
I encountered the same issue. Has anyone contacted you about it?

**Comment by jgnoonan** [comment]
No.  I did get the server up and running.  It's throwing a warning, but the server is starting.  Let me know if you need help.  It's easier to set up than I thought.  

On December 9, 2024 3:53:41 AM EST, YXXS242417 ***@***.***> wrote:
>I encountered the same issue. Has anyone contacted you about it?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2527302980
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Joe Noonan

**Comment by ripple-cny** [comment]
@YXXS242417, so I resolved the issue, and the server runs without error.  DM me for details.  I don't have the patience to write it all out. I worked with Intel, and they helped me get it running.   One thing is the sgx_default_qcnl.conf file located in the /etc directory should look like this:

`{
  // *** ATTENTION : This file is in JSON format so the keys are case sensitive. Don't change them.
  
  // This is a typical config file when used in Microsoft Azure environment

  "pccs_url": "https://global.acccache.azure.net/sgx/certification/v4/",

  "use_secure_cert": false,

  "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/",

  "pccs_api_version": "3.1",

  "retry_times": 6,

  "retry_delay": 5,

  "local_pck_url": "http://169.254.169.254/metadata/THIM/sgx/certification/v4/",

  "pck_cache_expire_hours": 48,

  "verify_collateral_cache_expire_hours": 48,

  "custom_request_options" : {
       "get_cert" : {
          "headers": {
              "metadata": "true"
          },
          "params": {
             "api-version": "2021-07-22-preview"
         }
      }
   }
}`

**Comment by YXXS242417** [comment]
Hello,Thank you for your enthusiastic and patient responses. Due to other tasks at hand, I had to temporarily set aside the handling of this issue and only got back to your message today. I sincerely apologize for the delay. Regarding the content of sgx_default_qcnl.conf that you provided, I have attempted to make changes, but they did not take effect. Could you tell me what other actions you took when you resolved this issue?

**Comment by ripple-cny** [comment]
Did you restart AESMD?

On December 17, 2024 2:20:41 AM EST, YXXS242417 ***@***.***> wrote:
>Hello,Thank you for your enthusiastic and patient responses. Due to other tasks at hand, I had to temporarily set aside the handling of this issue and only got back to your message today. I sincerely apologize for the delay. Regarding the content of sgx_default_qcnl.conf that you provided, I have attempted to make changes, but they did not take effect. Could you tell me what other actions you took when you resolved this issue?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2547676820
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Joe Noonan 
***@***.***

**Comment by YXXS242417** [comment]
> Did you restart AESMD?
> On December 17, 2024 2:20:41 AM EST, YXXS242417 ***@***.***> wrote: Hello,Thank you for your enthusiastic and patient responses. Due to other tasks at hand, I had to temporarily set aside the handling of this issue and only got back to your message today. I sincerely apologize for the delay. Regarding the content of sgx_default_qcnl.conf that you provided, I have attempted to make changes, but they did not take effect. Could you tell me what other actions you took when you resolved this issue? -- Reply to this email directly or view it on GitHub: [#5 (comment)](https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2547676820) You are receiving this because you commented. Message ID: ***@***.***>
> Joe Noonan ***@***.***

Not yet, I'm trying it now.

**Comment by YXXS242417** [comment]
> Did you restart AESMD?
> On December 17, 2024 2:20:41 AM EST, YXXS242417 ***@***.***> wrote: Hello,Thank you for your enthusiastic and patient responses. Due to other tasks at hand, I had to temporarily set aside the handling of this issue and only got back to your message today. I sincerely apologize for the delay. Regarding the content of sgx_default_qcnl.conf that you provided, I have attempted to make changes, but they did not take effect. Could you tell me what other actions you took when you resolved this issue? -- Reply to this email directly or view it on GitHub: [#5 (comment)](https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2547676820) You are receiving this because you commented. Message ID: ***@***.***>
> Joe Noonan ***@***.***

I did restart AESMD just now, and even restarted the entire server, but neither worked.

**Comment by jgnoonan** [comment]
What errors are you getting?  Look at syslog to see or run sudo systemctl status aesmd.

**Comment by YXXS242417** [comment]
This is the screenshot of the error I encountered after executing the command "./mvnw mn:run -Dmicronaut.environments=dev". My AESMD service status is active (running), and I have also checked /var/log/syslog, which did not provide any error messages.
![image](https://github.com/user-attachments/assets/7c154610-d99d-4c7c-8124-c6961f18ad9e)

**Comment by ripple-cny** [comment]
In the file src/main/resources/application-dev.yml, set simulation to false and restart AESMD.  Also type 'export SGX_MODE=HW' and the restart CDSI 

On December 17, 2024 9:39:27 PM EST, YXXS242417 ***@***.***> wrote:
>This is the screenshot of the error I encountered after executing the command "./mvnw mn:run -Dmicronaut.environments=dev". My AESMD service status is active (running), and I have also checked /var/log/syslog, which did not provide any error messages.
>![image](https://github.com/user-attachments/assets/7c154610-d99d-4c7c-8124-c6961f18ad9e)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2550182997
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Joe Noonan 
***@***.***

**Comment by YXXS242417** [comment]
I made the changes according to the method you provided and restarted CDSi. Now it's not throwing any errors. Please see the screenshot I provided. It no longer prints any output. Does this mean that I have successfully started CDSi?
![image](https://github.com/user-attachments/assets/fa9d7f1e-ab42-4a1f-86ed-3f4823392be1)

**Comment by jgnoonan** [comment]
Yes!!  Congratulations!!

On December 18, 2024 2:31:54 AM EST, YXXS242417 ***@***.***> wrote:
>I made the changes according to the method you provided and restarted CDSi. Now it's not throwing any errors. Please see the screenshot I provided. It no longer prints any output. Does this mean that I have successfully started CDSi?
>![image](https://github.com/user-attachments/assets/fa9d7f1e-ab42-4a1f-86ed-3f4823392be1)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2550562238
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Joe Noonan

**Comment by YXXS242417** [comment]
Thank you，thank you very much for your enthusiastic help. Without your assistance, I wouldn't know when I could get this service deployed. Here, I extend my sincere gratitude and heartfelt wishes to you. May the people you love be happy and fulfilled, and may the career you love flourish and prosper. If you have the opportunity to come to China, I will welcome you with the greatest enthusiasm.

**Comment by ripple-cny** [comment]
My pleasure.  I was in China about 6 years ago.  Beijing, Shanghai and Shenzen.  You have a beautiful country and the people were all so kind and generous.  I would love to come back someday!  If you need further help, let me know!

On December 18, 2024 8:25:56 PM EST, YXXS242417 ***@***.***> wrote:
>Thank you，thank you very much for your enthusiastic help. Without your assistance, I wouldn't know when I could get this service deployed. Here, I extend my sincere gratitude and heartfelt wishes to you. May the people you love be happy and fulfilled, and may the career you love flourish and prosper. If you have the opportunity to come to China, I will welcome you with the greatest enthusiasm.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2552582533
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Joe Noonan 
***@***.***

**Comment by romanvoloboev** [comment]
> I made the changes according to the method you provided and restarted CDSi. Now it's not throwing any errors. Please see the screenshot I provided. It no longer prints any output. Does this mean that I have successfully started CDSi? ![image](https://private-user-images.githubusercontent.com/58216036/396803931-fa9d7f1e-ab42-4a1f-86ed-3f4823392be1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Mzk5OTIsIm5iZiI6MTczNTgzOTY5MiwicGF0aCI6Ii81ODIxNjAzNi8zOTY4MDM5MzEtZmE5ZDdmMWUtYWI0Mi00YTFmLTg2ZWQtM2Y0ODIzMzkyYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE3NDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMDA1N2UwYmJkMmRiMjIxNmE0MDI4OWE0OGQ5MWI1NzRlMDg1YzRjNDg0NjJhYjgwMWJjZGUxNjg3N2Y0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CAF2Ie5QRHJ0c-UlRXfJtdE22QGwrPfpZmEJTxGX-D0)

Hello! 
Does your application works with mobile IOS application without any other errors?
I mean can you see your contacts list in application?

**Comment by YXXS242417** [comment]
> > I made the changes according to the method you provided and restarted CDSi. Now it's not throwing any errors. Please see the screenshot I provided. It no longer prints any output. Does this mean that I have successfully started CDSi? ![image](https://private-user-images.githubusercontent.com/58216036/396803931-fa9d7f1e-ab42-4a1f-86ed-3f4823392be1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Mzk5OTIsIm5iZiI6MTczNTgzOTY5MiwicGF0aCI6Ii81ODIxNjAzNi8zOTY4MDM5MzEtZmE5ZDdmMWUtYWI0Mi00YTFmLTg2ZWQtM2Y0ODIzMzkyYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE3NDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMDA1N2UwYmJkMmRiMjIxNmE0MDI4OWE0OGQ5MWI1NzRlMDg1YzRjNDg0NjJhYjgwMWJjZGUxNjg3N2Y0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CAF2Ie5QRHJ0c-UlRXfJtdE22QGwrPfpZmEJTxGX-D0)
> 
> Hello! Does your application works with mobile IOS application without any other errors like attestation errors when mobile app init this process? I mean can you see your contacts list in application?

Unfortunately, I am unable to see contacts on our development environment as it indicates a network error. I am using an SGX diagnostic tool from this repository: https://github.com/edgelesssys/sgx-troubleshoot.git to troubleshoot my errors, and it also suggests that there are network or proxy issues. Considering that my server is located in Shanghai, I am currently attempting to set up a VPN for it to enable unrestricted access to the global internet.

**Comment by romanvoloboev** [comment]
> https://github.com/edgelesssys/sgx-troubleshoot.git

thanks for the tool
after running it I'm getting next error
_attestation failed: verify_remote_report_
and have no idea what's is wrong

![image](https://github.com/user-attachments/assets/67608fbf-3e02-4160-b94a-00b3377d25ce)

**Comment by YXXS242417** [comment]
> > https://github.com/edgelesssys/sgx-troubleshoot.git
> 
> thanks for the tool after running it I'm getting next error _attestation failed: verify_remote_report_ and have no idea what's is wrong
> 
> ![image](https://private-user-images.githubusercontent.com/13852208/399938488-67608fbf-3e02-4160-b94a-00b3377d25ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMjc0MjUsIm5iZiI6MTczNjEyNzEyNSwicGF0aCI6Ii8xMzg1MjIwOC8zOTk5Mzg0ODgtNjc2MDhmYmYtM2UwMi00MTYwLWI5NGEtMDBiMzM3N2QyNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAxMzIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNDUzZTU2NTUxZjQwODBjMmM0ZmMwMjI3ODBmMzEyMDc1YTIxZWUyMzUyMjczNzNiM2ZhZDJkZTdiN2YxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GCvqIPRcOl1ulzAMOz7QfNq5-aGZ9JJkWXe7yC-QD9c)

Hello Romanvoloboev,I apologize for the delay in responding to your message. Due to the weekend, I was unable to see it sooner. I have encountered the error you mentioned before. My solution was to modify the /etc/sgx_default_qcnl.conf file and change the value of the collateral_service to https://global.acccache.azure.net/sgx/certification/v3/. After that, I restarted the aesm service. However, as I mentioned earlier, I encountered a network error, so I cannot guarantee that this modification will allow you to successfully start your CDSi service, but you can give it a try.

**Comment by jgnoonan** [comment]
Do not use the V3 APIs. Please update all the URLs in your configuration files to v4.

**Comment by YXXS242417** [comment]
> Do not use the V3 APIs. Please update all the URLs in your configuration files to v4.

Perhaps you are right, because whenever I try to use the contact service, it shows a network error as soon as I enter a phone number in the search box. I'm actually not sure how to resolve this error, and I'm just trying various possible methods.

**Comment by jgnoonan** [comment]
Are you using the correct enclave id?  When you pull the repo down, there is one that matches the code.  You need to change pom.xml from enclave_id=dev to this enclave ID.  I believe it starts with 0f....

**Comment by YXXS242417** [comment]
Of course, you're referring to the pom.xml file in the root directory, right? At the end of it, there's an ENCLAVE ID. I've modified it. Although mine starts with cc, after seeing your message, I changed it to an ENCLAVE ID that starts with 0f and restarted the CDSi. Unfortunately, it doesn't seem to have taken effect.

**Comment by ripple-cny** [comment]
ENCLAVE_ID=0f6fd79cdfdaa5b2e6337f534d3baf999318b0c462a7ac1f41297a3e4b424a57  Also you need to put the same enclave ID in application-dev.yml which is in the src/main/resources folder.  If you need to jump on a call, let me know. Warmest regards, Joseph G. ***@***.*** From: YXXS242417 ***@***.***>Date: Monday, January 6, 2025 at 5:04 AMTo: signalapp/ContactDiscoveryService-Icelake ***@***.***>Cc: ripple-cny ***@***.***>, Comment ***@***.***>Subject: Re: [signalapp/ContactDiscoveryService-Icelake] Cannot start server in dev mode (Issue #5)Of course, you're referring to the pom.xml file in the root directory, right? At the end of it, there's an ENCLAVE ID. I've modified it. Although mine starts with cc, after seeing your message, I changed it to an ENCLAVE ID that starts with 0f and restarted the CDSi. Unfortunately, it doesn't seem to have taken effect.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by YXXS242417** [comment]
> ENCLAVE_ID=0f6fd79cdfdaa5b2e6337f534d3baf999318b0c462a7ac1f41297a3e4b424a57  Also you need to put the same enclave ID in application-dev.yml which is in the src/main/resources folder.  If you need to jump on a call, let me know. Warmest regards, Joseph G. ***@***.*** From: YXXS242417 ***@***.***>Date: Monday, January 6, 2025 at 5:04 AMTo: signalapp/ContactDiscoveryService-Icelake ***@***.***>Cc: ripple-cny ***@***.***>, Comment ***@***.***>Subject: Re: [signalapp/ContactDiscoveryService-Icelake] Cannot start server in dev mode (Issue #5)Of course, you're referring to the pom.xml file in the root directory, right? At the end of it, there's an ENCLAVE ID. I've modified it. Although mine starts with cc, after seeing your message, I changed it to an ENCLAVE ID that starts with 0f and restarted the CDSi. Unfortunately, it doesn't seem to have taken effect.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I modified the two locations you mentioned and restarted the CDSi, but it didn't take effect.

**Comment by romanvoloboev** [comment]
maybe somebody from Signal guys will help us?
@jon-signal @eager-signal @ravi-signal

**Comment by kursattuncel** [comment]
Hello,
This thread has been very helpful for me. I was able to solve OE_UNSUPPORTED error by updating the simulation mode.

Now I'm getting the following error:

	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.signal.libsignal.cds2.DcapException: failure to attest remote SGX enclave code: AttestationError { message: "(evidence -> quote -> SgxPckExtension) could not parse required extension from PCK certificate: 1.2.840.113741.1.13.1.6" }
	at org.signal.libsignal.internal.Native.Cds2Metrics_extract(Native Method)

How can I solve this?

![Image](https://github.com/user-attachments/assets/983edf45-eead-42bc-b8b4-30d63ca32be5)

**Comment by ripple-cny** [comment]
If you do a sudo systemctl status aesmd, do you see any issues?  Make sure you are using the Intel DCAP Quote Provider Library and NOT the Azure one.From:  Yusuf Kursat Tuncel ***@***.***>Date:  Friday, January 24, 2025 at 3:43 PMTo:  signalapp/ContactDiscoveryService-Icelake ***@***.***>Cc:  ripple-cny ***@***.***>, Comment ***@***.***>Subject:  Re: [signalapp/ContactDiscoveryService-Icelake] Cannot start server in dev mode (Issue #5)Warmest regards, Joseph G. ***@***.***
Hello,
This thread has been very helpful for me. I was able to solve OE_UNSUPPORTED error by updating the simulation mode.
Now I'm getting the following error:
at java.base/java.lang.Thread.run(Thread.java:1583)

Caused by: org.signal.libsignal.cds2.DcapException: failure to attest remote SGX enclave code: AttestationError { message: "(evidence -> quote -> SgxPckExtension) could not parse required extension from PCK certificate: 1.2.840.113741.1.13.1.6" }
at org.signal.libsignal.internal.Native.Cds2Metrics_extract(Native Method)
How can I solve this?
image.png (view on web)

**Comment by kursattuncel** [comment]
No,
aesmd logs are clean.

And no, I'm not using Azure client.

Where do I find this PCK certificate? Is is specific to the machine? This is an Azure Confidential Cloud server.


root@test6:~#  systemctl status aesmd
● aesmd.service - Intel(R) Architectural Enclave Service Manager
     Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2025-01-24 20:39:03 UTC; 11min ago
    Process: 4583 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
    Process: 4592 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 4593 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 4594 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 4595 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 4596 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 4597 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=exited, status=0/SUCCESS)
   Main PID: 4598 (aesm_service)
      Tasks: 4 (limit: 9456)
     Memory: 5.5M
     CGroup: /system.slice/aesmd.service
             └─4598 /opt/intel/sgx-aesm-service/aesm/aesm_service

Jan 24 20:39:03 test6 systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.
Jan 24 20:39:03 test6 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Jan 24 20:39:03 test6 aesm_service[4597]: aesm_service: warning: Turn to daemon. Use "--no-daemon" option to execute in foreground.
Jan 24 20:39:03 test6 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Jan 24 20:39:03 test6 aesm_service[4598]: The server sock is 0x55fff014ab30

**Comment by romanvoloboev** [comment]
which instance type of azure confidential compute you rent?

**Comment by kursattuncel** [comment]
Hi,
I've created a new instance of DCsv3 type.

I've installed required dependencies and got back to the state where I left.

AESMD: working correct, no errors in the logs.
application-dev.yml: correct enclaveId and   simulated: false

This time, without any errors, it crashes during startup.

Any ideas?


![Image](https://github.com/user-attachments/assets/a29d75cf-ed49-4e81-940f-fc825b890802)

![Image](https://github.com/user-attachments/assets/d03f0c7e-5c6b-4875-9150-0831c07efd14)

**Comment by kursattuncel** [comment]
After the reboot, I get the following error:

01-28 05:50:20,824 [scheduled-executor-thread-1] WARN  org.signal.cdsi.enclave.Enclave - Failed to renew attestation
java.util.concurrent.CompletionException: org.signal.libsignal.cds2.DcapException: failure to attest remote SGX enclave code: AttestationError { message: "(endorsements -> CrlPckCert) [WRONG_TAG] [NESTED_ASN1_ERROR]" }
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.signal.libsignal.cds2.DcapException: failure to attest remote SGX enclave code: AttestationError { message: "(endorsements -> CrlPckCert) [WRONG_TAG] [NESTED_ASN1_ERROR]" }
	at org.signal.libsignal.internal.Native.Cds2Metrics_extract(Native Method)
	at org.signal.libsignal.cds2.Cds2Metrics.extract(Cds2Metrics.java:31)
	at org.signal.cdsi.enclave.Enclave.publishAttestationMetrics(Enclave.java:216)
	at org.signal.cdsi.enclave.Enclave.lambda$renewAttestation$3(Enclave.java:192)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at org.signal.cdsi.enclave.Enclave.lambda$runAsync$18(Enclave.java:440)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

![Image](https://github.com/user-attachments/assets/ee0ce480-7d1a-4736-92f1-cc5553b4212b)

**Comment by romanvoloboev** [comment]
Don’t install az-dcap-client, use instead dcap-qpl and dcap-qpl-dev. 
It might be not enough to delete it now and you will get another error like something not found.
Then just reinstall VM but without az-dcap-lib.

In case when application freezes you need to rebuild enclave with your own parameters in cdsi.conf, because that parameters adapted to VM with 120GB RAM and enclave will consume all your RAM and freeze the system.
Use chatGPT to calculate correct parameters for yours VM.

**Comment by ripple-cny** [comment]
It's running out of memory. That setting is for a production sized machine.  How much memory does your instance have?

On January 28, 2025 12:25:26 AM EST, Yusuf Kursat Tuncel ***@***.***> wrote:
>Hi,
>I've created a new instance of DCsv3 type.
>
>I've installed required dependencies and got back to the state where I left.
>
>AESMD: working correct, no errors in the logs.
>application-dev.yml: correct enclaveId and   simulated: false
>
>This time, without any errors, it crashes during startup.
>
>Any ideas?
>
>
>![Image](https://github.com/user-attachments/assets/a29d75cf-ed49-4e81-940f-fc825b890802)
>
>![Image](https://github.com/user-attachments/assets/d03f0c7e-5c6b-4875-9150-0831c07efd14)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2617920493
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Joe Noonan 
***@***.***

**Comment by ripple-cny** [comment]
You can remove the az-dcap-client client by running 

sudo apt remove --purge az-dcap-client -y


On January 28, 2025 2:11:47 AM EST, romanvoloboev ***@***.***> wrote:
>Don’t install az-dcap-client, use instead dcap-qpl and dcap-qpl-dev. 
>It might be not enough to delete it now and you will get another error like something not found.
>Then just reinstall VM but without az-dcap-lib.
>
>In case when application freezes you need to rebuild enclave with your own parameters in cdsi.conf, because that parameters adapted to VM with 120GB RAM and enclave will consume all your RAM and freeze the system.
>Use chatGPT to calculate correct parameters for yours VM.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/ContactDiscoveryService-Icelake/issues/5#issuecomment-2618086926
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Joe Noonan 
***@***.***

**Comment by kursattuncel** [comment]
Thank you. I'm able to start the server in dev mode.
One note is that, I've reinstall the server from ubuntu 22.04 and applied all the steps once again, the most critical was memory settings, and I was able to run the server.

**Comment by romanvoloboev** [comment]
It’s recommended to use Ubuntu 20, but if there are no problems with it than okay. 
Feel free to contact me via email (romanreal7 gmail com) in case any other questions related to this or other services.

**Comment by eager-signal** [comment]
It sounds like folks diagnosed their respective issues and got things working. In the future, the best place to discuss getting the software running is our [unofficial community forum](https://community.signalusers.org), and reserve GitHub issues for bug reports.
